[package]
name = "rosetun-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
eframe.workspace = true
rosetun-config.workspace = true
rosetun-core.workspace = true
rosetun-ipc.workspace = true
rosetun-processes.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[target.'cfg(windows)'.dependencies]
rosetun-shell.workspace = true
tray-icon.workspace = true
