[package]
name = "rosetun-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
eframe.workspace = true
fluent-bundle.workspace = true
unic-langid.workspace = true
rosetun-adapters.workspace = true
rosetun-config.workspace = true
rosetun-core.workspace = true
rosetun-ipc.workspace = true
rosetun-processes.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
fluent-syntax.workspace = true

[target.'cfg(windows)'.dependencies]
raw-window-handle.workspace = true
rosetun-shell.workspace = true
serde_json.workspace = true
tray-icon.workspace = true
rfd.workspace = true
