[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
repository = "https://github.com/eoftgge/rosetun"
license = "GPL-3.0-or-later"
publish = false

[workspace.dependencies]
rosetun-config = { path = "crates/rosetun-config" }
rosetun-core = { path = "crates/rosetun-core" }
rosetun-engine = { path = "crates/rosetun-engine" }
rosetun-engine-singbox = { path = "crates/rosetun-engine-singbox" }
rosetun-engine-xray = { path = "crates/rosetun-engine-xray" }
rosetun-hwid = { path = "crates/rosetun-hwid" }
rosetun-ipc = { path = "crates/rosetun-ipc" }
rosetun-shell = { path = "crates/rosetun-shell" }
rosetun-processes = { path = "crates/rosetun-processes" }
rosetun-routing = { path = "crates/rosetun-routing" }
rosetun-subscription = { path = "crates/rosetun-subscription" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
raw-window-handle = "0.6"
getrandom = "0.3"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_JobObjects",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_Pipes",
    "Win32_System_Rpc",
    "Win32_System_Services",
] }
url = "2.5.8"
base64 = "0.23.1"
percent-encoding = "2.3.2"
eframe = { version = "0.36", default-features = false, features = ["glow", "default_fonts", "accesskit", "links", "x11", "wayland"] }
tray-icon = { version = "0.26", default-features = false }
rfd = { version = "0.17", default-features = false }

[workspace.lints.rust]
missing_debug_implementations = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
todo = "allow"