[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/eoftgge/rosetun"

[workspace.dependencies]
rosetun-config = { path = "crates/rosetun-config" }
rosetun-engine = { path = "crates/rosetun-engine" }
rosetun-engine-singbox = { path = "crates/rosetun-engine-singbox" }
rosetun-engine-xray = { path = "crates/rosetun-engine-xray" }
rosetun-hwid = { path = "crates/rosetun-hwid" }
rosetun-ipc = { path = "crates/rosetun-ipc" }
rosetun-routing = { path = "crates/rosetun-routing" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_System_Rpc",
] }

[workspace.lints.rust]
missing_debug_implementations = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
todo = "allow"