[package]
name = "rosetun-helper-privileged"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
sha2 = "0.10"
rosetun-config.workspace = true
rosetun-engine.workspace = true
rosetun-engine-singbox.workspace = true
rosetun-engine-xray.workspace = true
rosetun-ipc.workspace = true
rosetun-routing.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_System_Registry", "Win32_System_SystemInformation", "Win32_System_SystemServices", "Win32_System_WindowsProgramming", "Win32_UI_WindowsAndMessaging"] }

[lints]
workspace = true
