[package]
name = "rosetun-processes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_UI_WindowsAndMessaging", "Win32_Graphics_Dwm"] }

[lints]
workspace = true
