[package]
name = "rosetun-engine-singbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
rosetun-config.workspace = true
rosetun-engine.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
ureq = { version = "3.4", default-features = false }

[lints]
workspace = true
