[package]
name = "rosetun-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rosetun-config.workspace = true
rosetun-subscription.workspace = true
rosetun-hwid.workspace = true
ureq = { version = "3.4", default-features = false, features = ["rustls", "platform-verifier", "gzip"] }
url.workspace = true
idna = "1"
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true