use super::{ErrorStrings, Language, Strings};

pub(crate) static EN: Strings = Strings {
    language: Language::English,
    errors: ErrorStrings {
        config_dir: "could not determine the configuration directory",
        config_access: "could not access {path}: {detail}",
        config_json: "invalid JSON in {path} at line {line}, column {column}",
        config_invalid: "invalid configuration in {path}: {detail}",
        config_version: "configuration version {found} is not supported (expected to be no higher than {expected})",
        config_dangling_node: "selected node {node} is not in subscription {subscription}",
        config_dangling_rule_set: "selected rule set {id} does not exist",
        config_inspect: "could not inspect the configuration file: {detail}",
        unsupported_scale: "unsupported interface scale",
        rule_set_not_found: "rule set does not exist",
        rule_not_found: "rule does not exist",
        rule_set_name_empty: "rule set name must not be empty",
        duplicate_rule: "this rule is already in the set",
        selected_rule_set_missing: "the selected rule set does not exist",
        invalid_domain: "enter a domain such as example.com or *.example.com",
        domain_is_ip: "this is an IP address, not a domain",
        single_label_domain: "enter a full domain such as example.com; use *.label for a top-level domain",
        invalid_process: "enter a process name such as app.exe or a full path to it",
        relative_path: "a process path must be absolute",
        invalid_resolver_ip: "enter the resolver's IP address, such as 1.1.1.1",
        invalid_resolver_name: "enter the resolver's TLS name, such as cloudflare-dns.com",
        invalid_port: "the port must be a number from 1 to 65535",
        invalid_dns_path: "the path must start with /",
        subscription_not_found: "subscription does not exist",
        subscription_name_empty: "subscription name must not be empty",
        node_not_found: "node is not in the specified subscription",
        request_settings_changed: "subscription request settings changed while the update was being fetched; retry the update",
        clock_before_epoch: "system clock is before the Unix epoch",
        already_added: "already added as {id}",
        url_already_added: "subscription URL is already added",
        ids_exhausted: "no subscription IDs are available",
        invalid_subscription_url: "invalid subscription URL",
        missing_host: "subscription URL requires a host",
        encrypted_happ_link: "Happ link is encrypted; ask your provider for a regular subscription link",
        url_scheme: "subscription URL must use http or https",
        import_link_invalid: "invalid subscription import link",
        import_link_without_url: "subscription import link requires a URL",
        import_link_multiple_urls: "subscription import link contains multiple URLs",
        import_link_nested: "too many nested subscription import links",
        fetch_user_agent: "User-Agent must contain printable ASCII characters",
        fetch_device_id: "device ID has an invalid format",
        fetch_failed: "subscription request failed",
        fetch_timeout: "subscription server did not respond in time",
        fetch_host_not_found: "subscription server name could not be resolved",
        fetch_connection: "could not connect to the subscription server",
        fetch_redirects: "too many redirects",
        fetch_insecure_redirect: "the server redirected to an unencrypted http:// address; refused",
        fetch_tls: "TLS error: {detail}; HTTPS inspection by an antivirus or a wrong system clock can cause this",
        fetch_too_large: "response too large",
        fetch_body: "could not read the subscription response",
        fetch_not_found: "subscription not found; panels with a device limit also answer 404 when no device ID is sent",
        fetch_not_found_retry: "subscription not found; panels with a device limit also answer 404 when no device ID is sent; turn on Send device ID and add the subscription again",
        fetch_access_denied: "access denied; the panel may only serve specific client apps",
        fetch_http_status: "subscription server returned HTTP {status}",
        parse_empty: "subscription body is empty",
        parse_web_page: "server returned a web page instead of a subscription",
        parse_unsupported_format: "subscription format is not supported",
        parse_unrecognized_format: "subscription format is not recognized",
        parse_invalid_utf8: "subscription body is not valid UTF-8",
        parse_invalid_json: "invalid subscription JSON at line {line}, column {column}",
        device_limit_reached: "device limit reached for this subscription; remove an old device in your provider's panel",
        device_id_rejected: "the panel did not accept this device ID",
        device_policy: "subscription access was refused by the device policy",
        no_usable_nodes: "subscription contains no usable nodes",
        provider_announce: "announce: {text}",
        provider_notice: "notice: {text}",
        skip_invalid_record: "record is invalid",
        skip_invalid_port: "port must be between 1 and 65535",
        skip_missing_field: "a required field is missing",
        skip_invalid_json: "invalid JSON at line {line}, column {column}",
        skip_unsupported_protocol: "protocol is not supported yet",
        skip_client_settings: "client settings are not node records",
        skip_vmess_format: "only the v2rayN JSON vmess link format is supported",
        skip_transport: "{transport} transport is not supported",
        skip_unknown_transport: "unknown transport is not supported",
        skip_tcp_header: "TCP HTTP header camouflage is not supported",
        skip_grpc_multi_mode: "gRPC multi mode is not supported",
        skip_encryption: "VLESS encryption is not supported",
        skip_flow: "flow is not supported",
        skip_security: "security mode is not supported",
        skip_reality_key: "Reality public key is missing",
        skip_shadowsocks_plugin: "Shadowsocks plugins are not supported",
        skip_shadowsocks_method: "Shadowsocks method is not supported",
        skip_service_record: "record contains a provider notice",
        process_list: "could not list running processes: {detail}",
        helper_transport: "unable to contact the Rosetun service: {detail}",
        helper_unexpected: "unexpected response from the Rosetun service",
        helper_closed: "the Rosetun service closed the connection",
        code_protocol_mismatch: "the Rosetun service speaks a different protocol version; update Rosetun",
        code_handshake_required: "the service expected a handshake first",
        code_not_privileged: "the service is not running with administrator rights",
        code_engine_failed: "the engine failed",
        code_routing_failed: "routing setup failed",
        code_busy: "the service is busy with another operation",
        code_invalid_state: "the tunnel is not in a state that allows this",
        code_unsupported_rules: "the engine does not support these rules",
        code_not_implemented: "the service does not support this yet",
        code_internal: "internal service error",
        autostart_read: "could not read the autostart setting: {detail}",
        autostart_write: "could not change autostart: {detail}",
        open_folder: "could not open the folder: {detail}",
    },
    connection: "Connection",
    rules: "Rules",
    settings: "Settings",
    settings_saved_instantly: "Changes are saved instantly",
    section_general: "General",
    section_network: "Network and DNS",
    section_service: "Service and log",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close_window: "Close",
    scale: "Scale",
    zoom_hint: "Ctrl+Plus and Ctrl+Minus zoom until the app closes.",
    reduce_motion: "Reduce motion",
    reduce_motion_detail: "No smooth transitions or pulsing: states change at once.",
    #[cfg(windows)]
    start_with_windows: "Start with Windows",
    #[cfg(windows)]
    start_with_windows_detail: "Opens in the tray when you sign in.",
    #[cfg(windows)]
    keep_in_tray: "Hide to tray on close",
    #[cfg(windows)]
    keep_in_tray_detail: "The close button hides the window. Quit from the tray menu.",
    connect_on_start: "Connect at startup",
    connect_on_start_detail: "Connects to the selected server as soon as Rosetun starts, including at Windows sign-in.",
    auto_reconnect: "Reconnect automatically",
    auto_reconnect_detail: "If the engine stops or the computer wakes from sleep, the service brings the tunnel back. With protection on, the internet stays blocked until then. Applies on next connect.",
    auto_update_subscriptions: "Update subscriptions automatically",
    auto_update_subscriptions_detail: "Every 12 hours, or as often as the provider asks. New servers and keys arrive on their own.",
    dns_through_tunnel: "DNS through the tunnel",
    dns_explanation: "Name lookups go to this DNS-over-HTTPS resolver through the server. It must be reachable from the server's exit.",
    dns_custom: "Custom",
    dns_custom_detail: "Enter an address",
    dns_reachable: "The resolver must be reachable from the VPN server.",
    resolver_ip: "Resolver IP",
    tls_name: "TLS name",
    port: "Port",
    dns_path: "Path",
    save: "Save",
    reset_to_default: "Reset to default",
    log_title: "Log",
    log_detail: "Useful when something breaks and you contact support.",
    service_label: "Rosetun service:",
    service_running: "running",
    service_stopped: "not running",
    service_detail: "The service runs the tunnel with system rights. Without it you can't connect.",
    reset_settings: "Reset settings",
    reset_settings_detail: "Subscriptions and rules stay; only the options on this screen go back to defaults.",
    reset_settings_question: "Reset settings?",
    reset_settings_body: "Interface, connection, DNS and log options go back to their defaults, and the kill switch turns off. Subscriptions, rules and starting with Windows stay as they are.",
    reset_disconnect_first: "Disconnect first.",
    verbose_log: "Verbose log",
    verbose_log_off_detail: "Records site addresses. Turn it on only to track down a problem: it turns itself off after a day. Applies on next connect.",
    verbose_log_on_detail: "Turns itself off in {hours}. While on, it records site addresses. Applies on next connect.",
    verbose_log_hour_one: "hour",
    verbose_log_hour_few: "hours",
    verbose_log_hour_many: "hours",
    about: "About",
    about_version_with_helper: "Version {app} · service {helper}",
    about_version_without_helper: "Version {app}",
    license_notice: "© 2026 Sandaar. Rosetun is free software under GPL-3.0-or-later and comes with no warranty.",
    licenses_folder: "Licenses",
    configuration_folder: "Configuration folder",
    log_file: "Log file",
    #[cfg(windows)]
    tray_open: "Open Rosetun",
    #[cfg(windows)]
    tray_quit: "Quit Rosetun",
    open_folder: "Open folder",
    connect: "Connect",
    unavailable: "Unavailable",
    disconnect: "Disconnect",
    retry: "Retry",
    reconnect: "Reconnect",
    connecting_action: "Connecting…",
    reconnecting_action: "Reconnecting…",
    working: "Working…",
    loading: "Loading configuration…",
    engine: "Engine",
    status_unknown: "Status unknown",
    disconnected: "Disconnected",
    connecting: "Connecting",
    connected: "Connected",
    connected_in_template: "Connected · {code}",
    reconnecting: "Reconnecting",
    failed: "Connection failed",
    failed_protected: "Connection failed · traffic blocked",
    traffic_blocked: "Traffic blocked",
    helper_unavailable: "Service unavailable",
    helper_unavailable_detail: "The Rosetun service is not running. Restart the computer or reinstall Rosetun. Subscriptions work without it.",
    service_down_title: "Rosetun service is not running",
    service_down_body: "Subscriptions and rules work, but you can't connect yet. Restart the computer or reinstall Rosetun.",
    details: "Details",
    hide_details: "Hide",
    select_server: "Select a server first",
    server_change: "Change ›",
    protocol: "Protocol",
    external_ip: "External IP",
    ip_own: "(yours)",
    ip_hidden: "Hidden",
    ip_show: "Show",
    ip_hide: "Hide",
    ip_unknown: "unknown",
    ip_pending: "…",
    session: "Session",
    traffic_down: "Download",
    traffic_up: "Upload",
    traffic_session: "This session",
    traffic_empty: "The chart appears once you connect",
    no_session: "not started",
    kill_switch: "Kill switch",
    protection: "Protection",
    kill_switch_detail: "Blocks all internet traffic if the tunnel drops.",
    default_rules: "Default · through VPN",
    next_connect: "Applies on next connect",
    turn_off_protection: "Turn off protection",
    keep_blocked: "Keep blocked",
    protection_warning: "Turning off protection will allow traffic outside the tunnel and may expose your real IP address.",
    add_subscription: "Add subscription",
    subscriptions_title: "Subscriptions",
    add_short: "+ Add",
    add_subtitle: "Servers will be imported automatically",
    subscription_url: "Subscription URL",
    paste: "Paste",
    name: "Name (optional)",
    name_placeholder: "Provider name",
    send_device_id: "Send device ID",
    device_id_explanation: "Some providers require a device ID to enforce device limits. Disable it only if your provider does not need it.",
    url_help: "HTTP(S) subscription URLs and supported app import links",
    http_warning: "This subscription uses HTTP; its token is transmitted without encryption.",
    add: "Add",
    adding: "Adding…",
    cancel: "Cancel",
    remove: "Remove",
    removing: "Removing…",
    remove_subscription: "Remove subscription?",
    rename_subscription: "Rename subscription",
    subscription_name: "Name",
    more_actions: "Actions",
    remove_detail: "The subscription and its servers will be removed.",
    remove_selected_warning: "This subscription contains the selected server. Its selection will be cleared; an existing tunnel will not be disconnected.",
    update: "Update",
    update_all: "Update all",
    updating: "Updating…",
    auto_update_every: "Auto: every {hours} h",
    auto_update_on: "Auto: on",
    servers_heading: "Servers",
    quota_used: "Used {used}",
    quota_used_of: "Used {used} of {total}",
    last_updated_template: "updated {age}",
    term_left_template: "{days} {unit} left",
    term_day_one: "day",
    term_day_few: "days",
    term_day_many: "days",
    term_under_day: "under a day",
    term_expired: "expired",
    never_updated: "not updated yet",
    no_subscriptions: "No subscriptions yet",
    empty_subscriptions: "Add a subscription to import servers and get connected.",
    no_servers: "No servers available",
    check_menu: "Check",
    check_quick: "Quick check",
    check_tcp: "TCP",
    check_full: "Full check",
    check_via_server: "through the server",
    check_while_connected: "while connected",
    check_hint: "Quick: time to open a connection to the server.\nFull: a real request through the server, works while connected.",
    ping_checking: "Checking…",
    ping_ms: "{ms} ms",
    ping_no_answer: "no response",
    ping_pending: "…",
    ping_best: "best {ms} ms",
    ping_tcp_hint: "TCP connection time only",
    ping_full_hint: "A request through the server answered",
    ping_fails: "not working",
    ping_fails_hint: "The server accepted no request: check the key, the protocol or the server's status",
    ping_unresolved: "address not found",
    ping_unresolved_hint: "The server name could not be resolved. With protection blocking the network, only servers given by IP can be checked",
    ping_unsupported: "not supported",
    full_check_busy: "A server check is already running",
    support: "Support",
    website: "Website",
    selection_cleared: "Selected server removed · choose another server",
    dismiss: "Dismiss",
    rules_title: "Routing rules",
    rules_tab_title: "Rules",
    rules_subtitle: "Decide what goes through the VPN and what goes direct. Apply to every subscription.",
    open_link: "Open ›",
    no_rules_yet: "No rules yet: everything goes by the default action",
    active: "Active",
    make_active: "Make active",
    new_set: "New set",
    create_rule_set: "Create rule set",
    rename: "Rename",
    delete: "Delete",
    basic: "Basic",
    set_name: "Set name",
    rename_rule_set: "Rename rule set",
    delete_rule_set: "Delete rule set?",
    delete_rule_set_detail: "This set and all its rules will be removed.",
    delete_active_rule_set_warning: "Connections will use Default · through VPN.",
    delete_rule: "Delete rule?",
    delete_rule_detail: "This rule will be removed from the set.",
    move_to_top: "Move to top",
    search_rules: "Search rules",
    all: "All",
    domains: "Websites",
    processes: "Apps",
    other: "Other",
    any_action: "Any action",
    proxy: "Through VPN",
    direct: "Direct",
    block: "Block",
    order_hint: "Checked from top to bottom; the first match wins. Drag to reorder.",
    reorder_disabled: "Clear the search and filters to reorder.",
    all_other_traffic: "All other traffic",
    default_fallback: "Used when no rule above matches",
    caption_this_address: "This address only",
    caption_subdomains: "Site and all subdomains",
    caption_keyword: "Address contains this word",
    caption_any_folder: "By name · any folder",
    caption_addresses: "IP addresses",
    default_rule_tooltip: "The default rule cannot be moved or removed.",
    no_rule_sets: "No rule sets yet. Connections use Default · through VPN.",
    no_rules_match: "No rules match the filter.",
    rules_next_connect: "Changes apply on next connect.",
    rules_templates: "Quick templates",
    template_add: "Add",
    template_added: "Added",
    template_remove_hint: "Click to remove the template from the set",
    template_redundant: "All other traffic already goes this way. The template helps when the last rule says otherwise.",
    template_contents: "Includes: {list}",
    caption_template: "Template · updates automatically",
    russian_sites_name: "Russian sites",
    russian_sites_description: "Domains in .ru, .su and .рф, plus VK and Yandex",
    messengers_name: "Messengers",
    messengers_description: "Telegram, Discord and WhatsApp: apps and websites",
    youtube_name: "YouTube",
    youtube_description: "The site, videos and thumbnails",
    torrents_name: "Torrents",
    torrents_description: "qBittorrent, uTorrent, BitTorrent, Transmission and others",
    new_rule_button: "+ Add rule",
    new_rule: "New rule",
    new_rule_subtitle: "It goes to the top of the list and is checked before the others.",
    edit: "Edit",
    edit_rule: "Edit rule",
    edit_rule_subtitle: "Its place in the list stays the same.",
    saving: "Saving…",
    what_to_route: "What to route",
    where_to_route: "Where to send it",
    rule_kind_app: "App",
    rule_kind_site: "Website",
    find_app: "Find an app",
    open_tab: "Open",
    all_processes: "All processes · {n}",
    found: "Found · {n}",
    typed_process: "Typed in",
    sites_label: "Website addresses, one per line",
    line_error: "Line {n}: {error}",
    more_errors: "And {k} more",
    add_rules_one: "Add {n} rule",
    add_rules_few: "Add {n} rules",
    add_rules_many: "Add {n} rules",
    include_subdomains: "Include subdomains",
    include_subdomains_detail: "youtube.com also covers m.youtube.com",
    advanced: "Advanced",
    full_path_detail: "The rule applies only to the program in this folder",
    #[cfg(windows)]
    browse: "Choose file…",
    #[cfg(windows)]
    choose_program: "Choose a program",
    #[cfg(windows)]
    programs: "Programs",
    refresh: "Refresh",
    loading_processes: "Loading processes…",
    no_running_processes: "No running processes found.",
    no_processes_match: "No processes match the filter.",
    path_unavailable: "path unavailable",
    match_by_full_path: "Match the full path",
    add_rule: "Add rule",
    adding_rule: "Adding rule…",
    language_title: "Language",
    language_system: "System",
};
