use super::Strings;

pub(crate) static EN: Strings = Strings {
    connection: "Connection",
    rules: "Rules",
    settings: "Settings",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close_window: "Close",
    interface: "Interface",
    scale: "Scale",
    zoom_hint: "Ctrl+Plus and Ctrl+Minus zoom until the app closes.",
    #[cfg(windows)]
    windows: "Windows",
    #[cfg(windows)]
    start_with_windows: "Start with Windows",
    #[cfg(windows)]
    start_with_windows_detail: "Opens in the tray when you sign in.",
    #[cfg(windows)]
    keep_in_tray: "Keep running in the tray",
    #[cfg(windows)]
    keep_in_tray_detail: "The close button hides the window. Quit from the tray menu.",
    dns_through_tunnel: "DNS through the tunnel",
    dns_explanation: "Name lookups go to this DNS-over-HTTPS resolver through the server. It must be reachable from the server's exit.",
    resolver_ip: "Resolver IP",
    tls_name: "TLS name",
    port: "Port",
    dns_path: "Path",
    save: "Save",
    reset_to_default: "Reset to default",
    engine_log: "Engine log",
    engine_log_detail: "Detail of the sing-box log the helper writes. Applies on next connect.",
    log_error: "Error",
    log_warn: "Warn",
    log_info: "Info",
    log_debug: "Debug",
    log_trace: "Trace",
    about: "About",
    helper_not_running: "Helper not running",
    configuration_folder: "Configuration folder",
    log_file: "Log file",
    #[cfg(windows)]
    tray_open: "Open Rosetun",
    #[cfg(windows)]
    tray_quit: "Quit Rosetun",
    open_folder: "Open folder",
    connect: "Connect",
    disconnect: "Disconnect",
    retry: "Retry",
    reconnect: "Reconnect",
    connecting_action: "Connecting…",
    reconnecting_action: "Reconnecting…",
    working: "Working…",
    loading: "Loading configuration…",
    engine: "Engine",
    active_server: "Active tunnel server",
    unknown_server: "Server no longer in configuration",
    status_unknown: "Status unknown",
    disconnected: "Disconnected",
    connecting: "Connecting",
    connected: "Connected",
    reconnecting: "Reconnecting",
    failed: "Connection failed",
    failed_protected: "Connection failed · traffic blocked",
    helper_unavailable: "Helper unavailable",
    helper_unavailable_detail: "Start the Rosetun helper externally. Subscriptions are still available.",
    select_server: "Select a server first",
    selected_server: "Selected server",
    session: "Session",
    kill_switch: "Kill switch",
    protection: "Protection",
    kill_switch_detail: "Blocks all internet traffic if the tunnel drops.",
    rule_set: "Rule set",
    default_rules: "Default · proxy all",
    next_connect: "Applies on next connect",
    turn_off_protection: "Turn off protection",
    keep_blocked: "Keep blocked",
    protection_warning: "Turning off protection will allow traffic outside the tunnel and may expose your real IP address.",
    add_subscription: "Add subscription",
    add_subtitle: "Servers will be imported automatically",
    subscription_url: "Subscription URL",
    paste: "Paste",
    name: "Name (optional)",
    name_placeholder: "Provider name",
    send_device_id: "Send device ID",
    device_id_explanation: "Some providers require a device ID to enforce device limits. Disable it only if your provider does not need it.",
    url_help: "HTTP(S) subscription URLs and supported app import links",
    http_warning: "This subscription uses HTTP; its token is transmitted without encryption.",
    add: "Add",
    adding: "Adding…",
    cancel: "Cancel",
    remove: "Remove",
    removing: "Removing…",
    remove_subscription: "Remove subscription?",
    remove_detail: "The subscription and its servers will be removed.",
    remove_selected_warning: "This subscription contains the selected server. Its selection will be cleared; an existing tunnel will not be disconnected.",
    update: "Update",
    update_all: "Update all",
    updating: "Updating…",
    subscription_reorder_disabled: "Wait for the current update to finish.",
    never_updated: "Not updated yet",
    no_subscriptions: "No subscriptions yet",
    empty_subscriptions: "Add a subscription to import servers and get connected.",
    no_servers: "No servers available",
    support: "Support",
    website: "Website",
    selection_cleared: "Selected server removed · choose another server",
    dismiss: "Dismiss",
    rules_title: "Routing rules",
    rules_subtitle: "Independent of subscriptions — the active set applies to every server.",
    open_rules: "Open rules",
    active: "Active",
    use_for_connections: "Use for connections",
    new_set: "New set",
    create_rule_set: "Create rule set",
    rename: "Rename",
    delete: "Delete",
    basic: "Basic",
    set_name: "Set name",
    rename_rule_set: "Rename rule set",
    delete_rule_set: "Delete rule set?",
    delete_rule_set_detail: "This set and all its rules will be removed.",
    delete_active_rule_set_warning: "Connections will use Default · proxy all.",
    delete_rule: "Delete rule?",
    delete_rule_detail: "This rule will be removed from the set.",
    search_rules: "Search rules",
    all: "All",
    domains: "Domains",
    processes: "Processes",
    other: "Other",
    proxy: "Proxy",
    direct: "Direct",
    block: "Block",
    domain: "Domain",
    process: "Process",
    keyword: "Keyword",
    r#type: "Type",
    value: "Value",
    target: "Target",
    enabled: "Enabled",
    order_hint: "Order from top to bottom sets priority.",
    reorder_disabled: "Clear the search and filters to reorder.",
    default: "Default",
    all_other_traffic: "All other traffic",
    default_fallback: "Used when no rule above matches",
    default_rule_tooltip: "The default rule cannot be moved or removed.",
    no_rule_sets: "No rule sets yet. Connections use Default · proxy all.",
    no_rules_match: "No rules match the filter.",
    rules_next_connect: "Changes apply on next connect.",
    new_rule_button: "+ Rule",
    new_rule: "New rule",
    new_rule_subtitle: "Applies to all subscriptions and goes to the top of the list — highest priority.",
    domain_input: "Domain or pattern",
    domain_placeholder: "example.com or *.example.com",
    domain_help: "example.com — only this domain · *.example.com — the domain and its subdomains",
    process_input: "Process name or full path to .exe",
    #[cfg(windows)]
    browse: "Browse…",
    #[cfg(windows)]
    choose_program: "Choose a program",
    #[cfg(windows)]
    programs: "Programs",
    process_placeholder: "app.exe or C:\\Apps\\app.exe",
    process_filter: "Filter by name or path",
    refresh: "Refresh",
    loading_processes: "Loading processes…",
    no_running_processes: "No running processes found.",
    no_processes_match: "No processes match the filter.",
    path_unavailable: "path unavailable",
    match_by_name: "Match by name",
    match_by_full_path: "Match by full path",
    add_rule: "Add rule",
    adding_rule: "Adding rule…",
};
