use super::{ErrorStrings, Language, Strings};

pub(crate) static EN: Strings = Strings {
    language: Language::English,
    errors: ErrorStrings {
        config_dir: "could not determine the configuration directory",
        config_access: "could not access {path}: {detail}",
        config_json: "invalid JSON in {path} at line {line}, column {column}",
        config_invalid: "invalid configuration in {path}: {detail}",
        config_version: "configuration version {found} is not supported (expected to be no higher than {expected})",
        config_dangling_node: "selected node {node} is not in subscription {subscription}",
        config_dangling_rule_set: "selected rule set {id} does not exist",
        config_inspect: "could not inspect the configuration file: {detail}",
        unsupported_scale: "unsupported interface scale",
        rule_set_not_found: "rule set does not exist",
        rule_not_found: "rule does not exist",
        rule_set_name_empty: "rule set name must not be empty",
        duplicate_rule: "this rule is already in the set",
        selected_rule_set_missing: "the selected rule set does not exist",
        invalid_domain: "enter a domain such as example.com or *.example.com",
        domain_is_ip: "this is an IP address, not a domain",
        single_label_domain: "enter a full domain such as example.com; use *.label for a top-level domain",
        invalid_process: "enter a process name such as app.exe or a full path to it",
        relative_path: "a process path must be absolute",
        invalid_resolver_ip: "enter the resolver's IP address, such as 8.8.8.8",
        invalid_resolver_name: "enter the resolver's TLS name, such as dns.google",
        invalid_port: "the port must be a number from 1 to 65535",
        invalid_dns_path: "the path must start with /",
        subscription_not_found: "subscription does not exist",
        node_not_found: "node is not in the specified subscription",
        request_settings_changed: "subscription request settings changed while the update was being fetched; retry the update",
        clock_before_epoch: "system clock is before the Unix epoch",
        already_added: "already added as {id}",
        url_already_added: "subscription URL is already added",
        ids_exhausted: "no subscription IDs are available",
        invalid_subscription_url: "invalid subscription URL",
        missing_host: "subscription URL requires a host",
        encrypted_happ_link: "Happ link is encrypted; ask your provider for a regular subscription link",
        url_scheme: "subscription URL must use http or https",
        import_link_invalid: "invalid subscription import link",
        import_link_without_url: "subscription import link requires a URL",
        import_link_multiple_urls: "subscription import link contains multiple URLs",
        import_link_nested: "too many nested subscription import links",
        fetch_user_agent: "User-Agent must contain printable ASCII characters",
        fetch_device_id: "device ID has an invalid format",
        fetch_failed: "subscription request failed",
        fetch_timeout: "subscription server did not respond in time",
        fetch_host_not_found: "subscription server name could not be resolved",
        fetch_connection: "could not connect to the subscription server",
        fetch_redirects: "too many redirects",
        fetch_insecure_redirect: "the server redirected to an unencrypted http:// address; refused",
        fetch_tls: "TLS error: {detail}; HTTPS inspection by an antivirus or a wrong system clock can cause this",
        fetch_too_large: "response too large",
        fetch_body: "could not read the subscription response",
        fetch_not_found: "subscription not found; panels with a device limit also answer 404 when no device ID is sent",
        fetch_not_found_retry: "subscription not found; panels with a device limit also answer 404 when no device ID is sent; turn on Send device ID and add the subscription again",
        fetch_access_denied: "access denied; the panel may only serve specific client apps",
        fetch_http_status: "subscription server returned HTTP {status}",
        parse_empty: "subscription body is empty",
        parse_web_page: "server returned a web page instead of a subscription",
        parse_unsupported_format: "subscription format is not supported",
        parse_unrecognized_format: "subscription format is not recognized",
        parse_invalid_utf8: "subscription body is not valid UTF-8",
        parse_invalid_json: "invalid subscription JSON at line {line}, column {column}",
        device_limit_reached: "device limit reached for this subscription; remove an old device in your provider's panel",
        device_id_rejected: "the panel did not accept this device ID",
        device_policy: "subscription access was refused by the device policy",
        no_usable_nodes: "subscription contains no usable nodes",
        provider_announce: "announce: {text}",
        provider_notice: "notice: {text}",
        skip_invalid_record: "record is invalid",
        skip_invalid_port: "port must be between 1 and 65535",
        skip_missing_field: "a required field is missing",
        skip_invalid_json: "invalid JSON at line {line}, column {column}",
        skip_unsupported_protocol: "protocol is not supported yet",
        skip_client_settings: "client settings are not node records",
        skip_vmess_format: "only the v2rayN JSON vmess link format is supported",
        skip_transport: "{transport} transport is not supported",
        skip_unknown_transport: "unknown transport is not supported",
        skip_tcp_header: "TCP HTTP header camouflage is not supported",
        skip_grpc_multi_mode: "gRPC multi mode is not supported",
        skip_encryption: "VLESS encryption is not supported",
        skip_flow: "flow is not supported",
        skip_security: "security mode is not supported",
        skip_reality_key: "Reality public key is missing",
        skip_shadowsocks_plugin: "Shadowsocks plugins are not supported",
        skip_shadowsocks_method: "Shadowsocks method is not supported",
        skip_service_record: "record contains a provider notice",
        process_list: "could not list running processes: {detail}",
        helper_transport: "unable to contact helper: {detail}",
        helper_unexpected: "unexpected response from helper",
        helper_closed: "helper closed the connection",
        code_protocol_mismatch: "the helper speaks a different protocol version; update Rosetun",
        code_handshake_required: "the helper expected a handshake first",
        code_not_privileged: "the helper is not running with administrator rights",
        code_engine_failed: "the engine failed",
        code_routing_failed: "routing setup failed",
        code_busy: "the helper is busy with another operation",
        code_invalid_state: "the tunnel is not in a state that allows this",
        code_unsupported_rules: "the engine does not support these rules",
        code_not_implemented: "the helper does not support this yet",
        code_internal: "internal helper error",
        autostart_read: "could not read the autostart setting: {detail}",
        autostart_write: "could not change autostart: {detail}",
        open_folder: "could not open the folder: {detail}",
    },
    connection: "Connection",
    rules: "Rules",
    settings: "Settings",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close_window: "Close",
    interface: "Interface",
    scale: "Scale",
    zoom_hint: "Ctrl+Plus and Ctrl+Minus zoom until the app closes.",
    #[cfg(windows)]
    windows: "Windows",
    #[cfg(windows)]
    start_with_windows: "Start with Windows",
    #[cfg(windows)]
    start_with_windows_detail: "Opens in the tray when you sign in.",
    #[cfg(windows)]
    keep_in_tray: "Keep running in the tray",
    #[cfg(windows)]
    keep_in_tray_detail: "The close button hides the window. Quit from the tray menu.",
    dns_through_tunnel: "DNS through the tunnel",
    dns_explanation: "Name lookups go to this DNS-over-HTTPS resolver through the server. It must be reachable from the server's exit.",
    resolver_ip: "Resolver IP",
    tls_name: "TLS name",
    port: "Port",
    dns_path: "Path",
    save: "Save",
    reset_to_default: "Reset to default",
    engine_log: "Engine log",
    engine_log_detail: "Detail of the sing-box log the helper writes. Applies on next connect.",
    log_error: "Error",
    log_warn: "Warn",
    log_info: "Info",
    log_debug: "Debug",
    log_trace: "Trace",
    about: "About",
    helper_not_running: "Helper not running",
    configuration_folder: "Configuration folder",
    log_file: "Log file",
    #[cfg(windows)]
    tray_open: "Open Rosetun",
    #[cfg(windows)]
    tray_quit: "Quit Rosetun",
    open_folder: "Open folder",
    connect: "Connect",
    disconnect: "Disconnect",
    retry: "Retry",
    reconnect: "Reconnect",
    connecting_action: "Connecting…",
    reconnecting_action: "Reconnecting…",
    working: "Working…",
    loading: "Loading configuration…",
    engine: "Engine",
    active_server: "Active tunnel server",
    unknown_server: "Server no longer in configuration",
    status_unknown: "Status unknown",
    disconnected: "Disconnected",
    connecting: "Connecting",
    connected: "Connected",
    reconnecting: "Reconnecting",
    failed: "Connection failed",
    failed_protected: "Connection failed · traffic blocked",
    traffic_blocked: "Traffic blocked",
    helper_unavailable: "Service unavailable",
    helper_unavailable_detail: "The Rosetun service is not running. Restart the computer or reinstall Rosetun. Subscriptions work without it.",
    select_server: "Select a server first",
    selected_server: "Selected server",
    session: "Session",
    no_session: "not started",
    kill_switch: "Kill switch",
    protection: "Protection",
    kill_switch_detail: "Blocks all internet traffic if the tunnel drops.",
    rule_set: "Rule set",
    default_rules: "Default · proxy all",
    next_connect: "Applies on next connect",
    turn_off_protection: "Turn off protection",
    keep_blocked: "Keep blocked",
    protection_warning: "Turning off protection will allow traffic outside the tunnel and may expose your real IP address.",
    add_subscription: "Add subscription",
    add_subtitle: "Servers will be imported automatically",
    subscription_url: "Subscription URL",
    paste: "Paste",
    name: "Name (optional)",
    name_placeholder: "Provider name",
    send_device_id: "Send device ID",
    device_id_explanation: "Some providers require a device ID to enforce device limits. Disable it only if your provider does not need it.",
    url_help: "HTTP(S) subscription URLs and supported app import links",
    http_warning: "This subscription uses HTTP; its token is transmitted without encryption.",
    add: "Add",
    adding: "Adding…",
    cancel: "Cancel",
    remove: "Remove",
    removing: "Removing…",
    remove_subscription: "Remove subscription?",
    remove_detail: "The subscription and its servers will be removed.",
    remove_selected_warning: "This subscription contains the selected server. Its selection will be cleared; an existing tunnel will not be disconnected.",
    update: "Update",
    update_all: "Update all",
    updating: "Updating…",
    subscription_reorder_disabled: "Wait for the current update to finish.",
    never_updated: "Not updated yet",
    no_subscriptions: "No subscriptions yet",
    empty_subscriptions: "Add a subscription to import servers and get connected.",
    no_servers: "No servers available",
    support: "Support",
    website: "Website",
    selection_cleared: "Selected server removed · choose another server",
    dismiss: "Dismiss",
    rules_title: "Routing rules",
    rules_subtitle: "Independent of subscriptions. The active set applies to every server.",
    open_rules: "Open rules",
    active: "Active",
    use_for_connections: "Use for connections",
    new_set: "New set",
    create_rule_set: "Create rule set",
    rename: "Rename",
    delete: "Delete",
    basic: "Basic",
    set_name: "Set name",
    rename_rule_set: "Rename rule set",
    delete_rule_set: "Delete rule set?",
    delete_rule_set_detail: "This set and all its rules will be removed.",
    delete_active_rule_set_warning: "Connections will use Default · proxy all.",
    delete_rule: "Delete rule?",
    delete_rule_detail: "This rule will be removed from the set.",
    search_rules: "Search rules",
    all: "All",
    domains: "Domains",
    processes: "Processes",
    other: "Other",
    proxy: "Proxy",
    direct: "Direct",
    block: "Block",
    domain: "Domain",
    process: "Process",
    keyword: "Keyword",
    r#type: "Type",
    value: "Value",
    target: "Target",
    enabled: "Enabled",
    order_hint: "Rules are checked from top to bottom, and the first match applies. Drag a rule to change the order.",
    reorder_disabled: "Clear the search and filters to reorder.",
    default: "Default",
    all_other_traffic: "All other traffic",
    default_fallback: "Used when no rule above matches",
    default_rule_tooltip: "The default rule cannot be moved or removed.",
    no_rule_sets: "No rule sets yet. Connections use Default · proxy all.",
    no_rules_match: "No rules match the filter.",
    rules_next_connect: "Changes apply on next connect.",
    new_rule_button: "+ Rule",
    new_rule: "New rule",
    new_rule_subtitle: "Applies to all subscriptions and goes to the top of the list, so it has the highest priority.",
    domain_input: "Domain or pattern",
    domain_placeholder: "example.com or *.example.com",
    domain_help: "example.com: only this domain · *.example.com: the domain and its subdomains",
    process_input: "Process name or full path to .exe",
    #[cfg(windows)]
    browse: "Browse…",
    #[cfg(windows)]
    choose_program: "Choose a program",
    #[cfg(windows)]
    programs: "Programs",
    process_placeholder: "app.exe or C:\\Apps\\app.exe",
    process_filter: "Filter by name or path",
    refresh: "Refresh",
    loading_processes: "Loading processes…",
    no_running_processes: "No running processes found.",
    no_processes_match: "No processes match the filter.",
    path_unavailable: "path unavailable",
    match_by_name: "Match by name",
    match_by_full_path: "Match by full path",
    add_rule: "Add rule",
    adding_rule: "Adding rule…",
    language_title: "Language",
    language_system: "System",
};
