use super::{ErrorStrings, Language, Strings};

pub(crate) static RU: Strings = Strings {
    language: Language::Russian,
    errors: ErrorStrings {
        config_dir: "не удалось определить папку конфигурации",
        config_access: "нет доступа к {path}: {detail}",
        config_json: "ошибка JSON в {path}: строка {line}, столбец {column}",
        config_invalid: "неверная конфигурация в {path}: {detail}",
        config_version: "версия конфигурации {found} не поддерживается (нужна не выше {expected})",
        config_dangling_node: "выбранного сервера {node} нет в подписке {subscription}",
        config_dangling_rule_set: "выбранного набора правил {id} нет",
        config_inspect: "не удалось проверить файл конфигурации: {detail}",
        unsupported_scale: "такой масштаб интерфейса не поддерживается",
        rule_set_not_found: "набор правил не найден",
        rule_not_found: "правило не найдено",
        rule_set_name_empty: "название набора не может быть пустым",
        duplicate_rule: "такое правило уже есть в наборе",
        selected_rule_set_missing: "выбранного набора правил нет",
        invalid_domain: "введите домен, например example.com или *.example.com",
        domain_is_ip: "это IP-адрес, а не домен",
        single_label_domain: "введите полный домен, например example.com; для зоны целиком используйте *.ru",
        invalid_process: "введите имя процесса, например app.exe, или полный путь к нему",
        relative_path: "путь к процессу должен быть полным",
        invalid_resolver_ip: "введите IP-адрес резолвера, например 8.8.8.8",
        invalid_resolver_name: "введите TLS-имя резолвера, например dns.google",
        invalid_port: "порт должен быть числом от 1 до 65535",
        invalid_dns_path: "путь должен начинаться с /",
        subscription_not_found: "подписка не найдена",
        node_not_found: "сервера нет в этой подписке",
        request_settings_changed: "настройки запроса подписки изменились во время обновления; обновите ещё раз",
        clock_before_epoch: "системные часы показывают дату раньше 1970 года",
        already_added: "уже добавлена как {id}",
        url_already_added: "этот адрес подписки уже добавлен",
        ids_exhausted: "закончились идентификаторы подписок",
        invalid_subscription_url: "неверный адрес подписки",
        missing_host: "в адресе подписки нет хоста",
        encrypted_happ_link: "ссылка Happ зашифрована; попросите у провайдера обычную ссылку на подписку",
        url_scheme: "адрес подписки должен начинаться с http:// или https://",
        import_link_invalid: "неверная ссылка импорта подписки",
        import_link_without_url: "в ссылке импорта нет адреса подписки",
        import_link_multiple_urls: "в ссылке импорта несколько адресов подписки",
        import_link_nested: "слишком много вложенных ссылок импорта",
        fetch_user_agent: "User-Agent может содержать только печатные символы ASCII",
        fetch_device_id: "неверный формат ID устройства",
        fetch_failed: "не удалось загрузить подписку",
        fetch_timeout: "сервер подписки не ответил вовремя",
        fetch_host_not_found: "не удалось найти сервер подписки по имени",
        fetch_connection: "не удалось подключиться к серверу подписки",
        fetch_redirects: "слишком много перенаправлений",
        fetch_insecure_redirect: "сервер перенаправил на незашифрованный адрес http://, переход отклонён",
        fetch_tls: "ошибка TLS: {detail}; так бывает, если антивирус проверяет HTTPS-трафик или на компьютере неверное время",
        fetch_too_large: "ответ сервера подписки слишком большой",
        fetch_body: "не удалось прочитать ответ сервера подписки",
        fetch_not_found: "подписка не найдена; панели с лимитом устройств отвечают так же, если ID устройства не отправлен",
        fetch_not_found_retry: "подписка не найдена; панели с лимитом устройств отвечают так же, если ID устройства не отправлен; включите «Отправлять ID устройства» и добавьте подписку снова",
        fetch_access_denied: "доступ запрещён; возможно, панель работает только с определёнными приложениями",
        fetch_http_status: "сервер подписки вернул ошибку HTTP {status}",
        parse_empty: "подписка пустая",
        parse_web_page: "сервер вернул веб-страницу вместо подписки",
        parse_unsupported_format: "формат подписки не поддерживается",
        parse_unrecognized_format: "формат подписки не распознан",
        parse_invalid_utf8: "подписка не в кодировке UTF-8",
        parse_invalid_json: "ошибка JSON в подписке: строка {line}, столбец {column}",
        device_limit_reached: "достигнут лимит устройств; удалите старое устройство в панели провайдера",
        device_id_rejected: "панель не приняла ID этого устройства",
        device_policy: "доступ к подписке закрыт правилами для устройств",
        no_usable_nodes: "в подписке нет подходящих серверов",
        provider_announce: "объявление провайдера: {text}",
        provider_notice: "уведомление провайдера: {text}",
        skip_invalid_record: "неверная запись",
        skip_invalid_port: "порт должен быть числом от 1 до 65535",
        skip_missing_field: "нет обязательного поля",
        skip_invalid_json: "ошибка JSON: строка {line}, столбец {column}",
        skip_unsupported_protocol: "протокол пока не поддерживается",
        skip_client_settings: "это настройки клиента, а не сервер",
        skip_vmess_format: "ссылки vmess поддерживаются только в формате JSON от v2rayN",
        skip_transport: "транспорт {transport} не поддерживается",
        skip_unknown_transport: "неизвестный транспорт не поддерживается",
        skip_tcp_header: "маскировка TCP под HTTP не поддерживается",
        skip_grpc_multi_mode: "режим gRPC multi не поддерживается",
        skip_encryption: "шифрование VLESS не поддерживается",
        skip_flow: "такой flow не поддерживается",
        skip_security: "такой режим security не поддерживается",
        skip_reality_key: "нет открытого ключа Reality",
        skip_shadowsocks_plugin: "плагины Shadowsocks не поддерживаются",
        skip_shadowsocks_method: "такой метод Shadowsocks не поддерживается",
        skip_service_record: "запись содержит уведомление провайдера",
        process_list: "не удалось получить список процессов: {detail}",
        helper_transport: "нет связи со службой: {detail}",
        helper_unexpected: "неожиданный ответ службы",
        helper_closed: "служба закрыла соединение",
        code_protocol_mismatch: "служба использует другую версию протокола; обновите Rosetun",
        code_handshake_required: "нарушен порядок обмена со службой",
        code_not_privileged: "служба запущена без прав администратора",
        code_engine_failed: "сбой ядра",
        code_routing_failed: "не удалось настроить маршрутизацию",
        code_busy: "служба занята другой операцией",
        code_invalid_state: "в текущем состоянии туннеля это невозможно",
        code_unsupported_rules: "ядро не поддерживает эти правила",
        code_not_implemented: "служба пока этого не умеет",
        code_internal: "внутренняя ошибка службы",
        autostart_read: "не удалось прочитать настройку автозапуска: {detail}",
        autostart_write: "не удалось изменить автозапуск: {detail}",
        open_folder: "не удалось открыть папку: {detail}",
    },
    connection: "Подключение",
    rules: "Правила",
    settings: "Настройки",
    minimize: "Свернуть",
    maximize: "Развернуть",
    restore: "Восстановить",
    close_window: "Закрыть",
    interface: "Интерфейс",
    scale: "Масштаб",
    zoom_hint: "Ctrl+Plus и Ctrl+Minus меняют масштаб до закрытия программы.",
    #[cfg(windows)]
    windows: "Windows",
    #[cfg(windows)]
    start_with_windows: "Запускать вместе с Windows",
    #[cfg(windows)]
    start_with_windows_detail: "Открывается в трее при входе в систему.",
    #[cfg(windows)]
    keep_in_tray: "Оставаться в трее",
    #[cfg(windows)]
    keep_in_tray_detail: "Крестик прячет окно. Выйти можно из меню в трее.",
    connect_on_start: "Подключаться при запуске",
    connect_on_start_detail: "Подключается к выбранному серверу сразу после запуска программы, в том числе при входе в Windows.",
    auto_reconnect: "Переподключаться при обрыве",
    auto_reconnect_detail: "Если ядро остановилось или компьютер вышел из сна, служба поднимает туннель заново. С защитой интернет заблокирован, пока туннель не вернётся. Применится при следующем подключении.",
    auto_update_subscriptions: "Обновлять подписки автоматически",
    auto_update_subscriptions_detail: "Раз в 12 часов или так часто, как просит провайдер. Новые серверы и ключи приходят сами.",
    dns_through_tunnel: "DNS через туннель",
    dns_explanation: "DNS-запросы идут к этому резолверу DNS-over-HTTPS через сервер. Резолвер должен быть доступен с выхода сервера.",
    resolver_ip: "IP резолвера",
    tls_name: "Имя TLS",
    port: "Порт",
    dns_path: "Путь",
    save: "Сохранить",
    reset_to_default: "Сбросить",
    log_title: "Журнал",
    verbose_log: "Подробный журнал",
    verbose_log_off_detail: "Записывает адреса сайтов. Включайте, только чтобы найти проблему: через сутки выключится сам. Применится при следующем подключении.",
    verbose_log_on_detail: "Выключится сам через {hours}. Пока включён, записывает адреса сайтов. Применится при следующем подключении.",
    verbose_log_hour_one: "час",
    verbose_log_hour_few: "часа",
    verbose_log_hour_many: "часов",
    about: "О программе",
    helper_not_running: "Служба не запущена",
    configuration_folder: "Папка конфигурации",
    log_file: "Файл журнала",
    #[cfg(windows)]
    tray_open: "Открыть Rosetun",
    #[cfg(windows)]
    tray_quit: "Выйти из Rosetun",
    open_folder: "Открыть папку",
    connect: "Подключиться",
    disconnect: "Отключиться",
    retry: "Повторить",
    reconnect: "Переподключиться",
    connecting_action: "Подключение…",
    reconnecting_action: "Переподключение…",
    working: "Выполняется…",
    loading: "Загрузка конфигурации…",
    engine: "Ядро",
    active_server: "Сервер текущего туннеля",
    unknown_server: "Сервера больше нет в конфигурации",
    status_unknown: "Состояние неизвестно",
    disconnected: "Отключено",
    connecting: "Подключение",
    connected: "Подключено",
    reconnecting: "Переподключение",
    failed: "Не удалось подключиться",
    failed_protected: "Не удалось подключиться · трафик заблокирован",
    traffic_blocked: "Трафик заблокирован",
    helper_unavailable: "Служба недоступна",
    helper_unavailable_detail: "Служба Rosetun не запущена. Перезагрузите компьютер или переустановите Rosetun. Подписки работают и без неё.",
    select_server: "Сначала выберите сервер",
    selected_server: "Выбранный сервер",
    session: "Сеанс",
    no_session: "не начат",
    kill_switch: "Kill switch",
    protection: "Защита",
    kill_switch_detail: "Блокирует весь интернет-трафик, если туннель оборвётся.",
    rule_set: "Набор правил",
    default_rules: "По умолчанию · всё через прокси",
    next_connect: "Применится при следующем подключении",
    turn_off_protection: "Отключить защиту",
    keep_blocked: "Оставить блокировку",
    protection_warning: "Без защиты трафик пойдёт мимо туннеля, и ваш настоящий IP-адрес может стать виден.",
    add_subscription: "Добавить подписку",
    add_subtitle: "Серверы загрузятся автоматически",
    subscription_url: "Адрес подписки",
    paste: "Вставить",
    name: "Название (необязательно)",
    name_placeholder: "Название провайдера",
    send_device_id: "Отправлять ID устройства",
    device_id_explanation: "Некоторые провайдеры ограничивают число устройств по их ID. Отключайте, только если ваш провайдер его не требует.",
    url_help: "Адреса подписок HTTP(S) и ссылки импорта из поддерживаемых приложений",
    http_warning: "Подписка работает по HTTP: её токен передаётся без шифрования.",
    add: "Добавить",
    adding: "Добавление…",
    cancel: "Отмена",
    remove: "Удалить",
    removing: "Удаление…",
    remove_subscription: "Удалить подписку?",
    remove_detail: "Подписка и её серверы будут удалены.",
    remove_selected_warning: "В этой подписке выбранный сервер. Выбор будет сброшен; текущий туннель не отключится.",
    update: "Обновить",
    update_all: "Обновить все",
    updating: "Обновление…",
    subscription_reorder_disabled: "Дождитесь окончания обновления.",
    never_updated: "Ещё не обновлялась",
    no_subscriptions: "Подписок пока нет",
    empty_subscriptions: "Добавьте подписку, чтобы загрузить серверы и подключиться.",
    no_servers: "Нет доступных серверов",
    ping_check: "Проверить пинг",
    ping_checking: "Проверяем…",
    ping_ms: "{ms} мс",
    ping_no_answer: "нет ответа",
    ping_pending: "…",
    ping_best: "лучший {ms} мс",
    ping_tunnel_up: "Пинг проверяется, пока туннель отключён: через туннель все серверы показались бы мгновенными.",
    support: "Поддержка",
    website: "Сайт",
    selection_cleared: "Выбранный сервер удалён · выберите другой",
    dismiss: "Скрыть",
    rules_title: "Правила маршрутизации",
    rules_subtitle: "Не зависят от подписок. Активный набор действует для всех серверов.",
    open_rules: "Открыть правила",
    active: "Активный",
    use_for_connections: "Использовать для подключений",
    new_set: "Новый набор",
    create_rule_set: "Создать набор правил",
    rename: "Переименовать",
    delete: "Удалить",
    basic: "Основной",
    set_name: "Название набора",
    rename_rule_set: "Переименовать набор правил",
    delete_rule_set: "Удалить набор правил?",
    delete_rule_set_detail: "Набор и все его правила будут удалены.",
    delete_active_rule_set_warning: "Подключения будут использовать «По умолчанию · всё через прокси».",
    delete_rule: "Удалить правило?",
    delete_rule_detail: "Правило будет удалено из набора.",
    search_rules: "Поиск правил",
    all: "Все",
    domains: "Домены",
    processes: "Процессы",
    other: "Другие",
    proxy: "Прокси",
    direct: "Напрямую",
    block: "Блокировать",
    domain: "Домен",
    process: "Процесс",
    keyword: "Ключевое слово",
    r#type: "Тип",
    value: "Значение",
    target: "Действие",
    enabled: "Включено",
    order_hint: "Правила проверяются сверху вниз, срабатывает первое подходящее. Перетащите правило, чтобы изменить порядок.",
    reorder_disabled: "Очистите поиск и фильтры, чтобы менять порядок.",
    default: "По умолчанию",
    all_other_traffic: "Весь остальной трафик",
    default_fallback: "Если не подошло ни одно правило выше",
    default_rule_tooltip: "Правило по умолчанию нельзя перемещать или удалять.",
    no_rule_sets: "Наборов правил пока нет. Подключения используют «По умолчанию · всё через прокси».",
    no_rules_match: "Нет правил под этот фильтр.",
    rules_next_connect: "Изменения применятся при следующем подключении.",
    new_rule_button: "+ Правило",
    new_rule: "Новое правило",
    new_rule_subtitle: "Действует для всех подписок и встаёт в начало списка, поэтому срабатывает первым.",
    domain_input: "Домен или шаблон",
    domain_placeholder: "example.com или *.example.com",
    domain_help: "example.com: только этот домен · *.example.com: домен и его поддомены",
    process_input: "Имя процесса или полный путь к .exe",
    #[cfg(windows)]
    browse: "Обзор…",
    #[cfg(windows)]
    choose_program: "Выберите программу",
    #[cfg(windows)]
    programs: "Программы",
    process_placeholder: "app.exe или C:\\Apps\\app.exe",
    process_filter: "Фильтр по имени или пути",
    refresh: "Обновить",
    loading_processes: "Загрузка процессов…",
    no_running_processes: "Запущенных процессов не найдено.",
    no_processes_match: "Нет процессов под этот фильтр.",
    path_unavailable: "путь недоступен",
    match_by_name: "По имени",
    match_by_full_path: "По полному пути",
    add_rule: "Добавить правило",
    adding_rule: "Добавление правила…",
    language_title: "Язык",
    language_system: "Как в системе",
};
